ECHO OFF
CLS
echo ...............................................
echo .                                             .
echo ..                                           ..
echo ...                                         ...	
echo ....                                       ....
echo              Gerador de etiqueta
echo ....                                       ....
echo ...                                         ...
echo ..                                           ..
echo .                                             .
echo ...............................................
TYPE etq.txt > \\10.144.200.93\ppa01
echo .                                             .
echo ..                                           ..
echo ...                                         ...	
echo ....                                       ....
echo            JOYSON SAFETY SYSTEMS
echo ....                                       ....
echo ...                                         ...
echo ..                                           ..
echo .                                             .
echo ...............................................

del etq.txt /s

PING -n 5 127.0.0.1 >NUL

cls

echo FECHANDO O PROGRAMA! 
PING -n 3 127.0.0.1 >NUL

